myData=read.csv("D:/veja.csv") 
print(head(myData)) 
mean=mean(myData$age) 
print(mean) 
median=median(myData$age) 
print(median) 
variance = var(myData$age) 
print(variance) 
standard = sd(myData$age) 
print(standard) 
max = max(myData$age) 
min = min(myData$age) 
range = max - min
print(range) 
quartiles = quantile(myData$age) 
print(quartiles) 