library(stats)
setwd("C:/Users/Dell")
dataSet=read.csv("CardioGoodFitness.csv")
print(head(dataSet))
mean=mean(dataSet$Weight)
print(mean)
median=median(dataSet$Weight)
print(median)
variance = var(dataSet$Weight)
print(variance)
standard = sd(dataSet$Weight)
print(standard)
max = max(dataSet$Weight)
min = min(dataSet$Weight)
range = max - min
print(range)
quartiles = quantile(dataSet$Weight)
print(quartiles)